version: '2.0'

networks:
  default_network:
    external: true
services:
  database:
    image: mysql:5.6
    ports:
      - "3306:3306"
    restart: always
    networks:
      # The preconfigured docker network where MySQL will be initialized
      - default_network
    environment:
      MYSQL_DATABASE: "oauth"
      MYSQL_USER: "oauth_user"
      MYSQL_PASSWORD: "oauth_password"
      MYSQL_ROOT_PASSWORD: "oauth_root_password"